### ISSUE TITLE
JSONDecodeError problem after restart if no data from station

### ISSUE THREAD

**Issue by sipimokus** [amaximus/bkk_stop#13]
Hello!

I restarted my HASS after midnight, when no transports some bus stations, and I got this error and these sensors not created:
```
Logger: homeassistant.components.sensor
Source: custom_components/bkk_stop/sensor.py:122
Integration: Érzékelő (documentation, issues)
First occurred: 00:27:04 (3 occurrences)
Last logged: 00:27:05

Error adding entities for domain sensor with platform bkk_stop
Error while setting up bkk_stop platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 382, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 607, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 715, in add_to_platform_finish
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 486, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 526, in _async_write_ha_state
    extra_state_attributes = self.device_state_attributes
  File "/config/custom_components/bkk_stop/sensor.py", line 122, in device_state_attributes
    return json.loads(bkkjson)
  File "/usr/local/lib/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.9/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Unterminated string starting at: line 1 column 16 (char 15)
```

At the morning I got back the sensors again. :)

BKK Version: 2.0.0
HASS: 2021.11.5

PS.: Thank you very much the json attribute usage, very impressive and helpful for custom designs!

**Comment by sipimokus** [comment]
Pull request for fix, and some changes for json object:
https://github.com/amaximus/bkk_stop/pull/14

**Comment by amaximus** [comment]
Merged. Please check on your side too and if found ok please close this issue tracker.

**Comment by sipimokus** [comment]
I tested, its works well. Thank you for the PR!
