### ISSUE TITLE
The bus data is not loading.

### ISSUE THREAD

**Issue by v1k70rk4** [amaximus/bkk_stop#22]
Hello, starting from 14:30 today, I am encountering the following error. Theoretically, nothing has changed.
I appreciate your work both in advance and afterwards. It is very useful.

> Logger: homeassistant.components.sensor
> Source: helpers/aiohttp_client.py:67
> Integration: Érzékelő (documentation, issues)
> First occurred: 16:52:11 (2 occurrences)
> Last logged: 16:52:11
> 
> bkk_stop: Error on device update!
> Traceback (most recent call last):
>   File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 521, in _async_add_entity
>     await entity.async_device_update(warning=False)
>   File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 748, in async_device_update
>     await task
>   File "/config/custom_components/bkk_stop/sensor.py", line 167, in async_update
>     self._bkkdata = await response.json()
>   File "/usr/src/homeassistant/homeassistant/helpers/aiohttp_client.py", line 67, in json
>     return await super().json(*args, loads=loads, **kwargs)
>   File "/usr/local/lib/python3.10/site-packages/aiohttp/client_reqrep.py", line 1104, in json
>     raise ContentTypeError(
> aiohttp.client_exceptions.ContentTypeError: 0, message='Attempt to decode JSON with unexpected mimetype: text/plain;charset=iso-8859-1', url=URL('https://go.bkk.hu/api/query/v1/ws/otp/api/where/arrivals-and-departures-for-stop.json?key=apaiary-test&version=3&appVersion=apiary-1.0&onlyDepartures=true&stopId=BKK_F02647&minutesAfter=25')
>

**Comment by v1k70rk4** [comment]
It may have been a temporary problem, it fixed itself this morning.
